CREATE TABLE IF NOT EXISTS media
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  creator VARCHAR(255),
  collection VARCHAR(255),
  genre VARCHAR(255),
  status VARCHAR(255),
  type VARCHAR(255)
);

ALTER TABLE media ALTER COLUMN status SET DEFAULT 'WANT';